"""add role to user

Revision ID: 0052dd790090
Revises: 96893a1dc738
Create Date: 2026-08-11 15:02:24.021398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0052dd790090'
down_revision = '96893a1dc738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Tambahkan kolom role tanpa NOT NULL dulu
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # Isi semua baris yang sudah ada dengan nilai default 'viewer'
    # Ganti 'user' dengan nama tabel yang sesuai jika berbeda
    op.execute("UPDATE \"user\" SET role = 'viewer' WHERE role IS NULL")

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Sekarang beri NOT NULL constraint
        batch_op.alter_column('role', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
