"""add tags to ip address

Revision ID: 02eeb5184b9e
Revises: 661262f8c62e
Create Date: 2026-09-07 13:54:51.071013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02eeb5184b9e'
down_revision = '661262f8c62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_address', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
