"""add alert_threshold to subnet

Revision ID: 2c83c1f8102e
Revises: b7dc1b00a39c
Create Date: 2026-08-10 15:58:03.830753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c83c1f8102e'
down_revision = 'b7dc1b00a39c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_threshold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subnet', schema=None) as batch_op:
        batch_op.drop_column('alert_threshold')

    # ### end Alembic commands ###
