"""add port mapping model

Revision ID: 6dfba72a1cb7
Revises: e56d2754c37b
Create Date: 2026-09-06 19:29:04.775018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfba72a1cb7'
down_revision = 'e56d2754c37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address_id', sa.Integer(), nullable=True),
    sa.Column('switch_name', sa.String(length=100), nullable=False),
    sa.Column('port_number', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ip_address_id'], ['ip_address.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('switch_name', 'port_number', name='unique_switch_port')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('port_mapping')
    # ### end Alembic commands ###
