"""add audit trail columns

Revision ID: 96893a1dc738
Revises: 2c83c1f8102e
Create Date: 2026-08-11 11:50:17.843410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96893a1dc738'
down_revision = '2c83c1f8102e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('object_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('object_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('changes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_column('changes')
        batch_op.drop_column('object_id')
        batch_op.drop_column('object_type')

    # ### end Alembic commands ###
