"""add total_ports to port mapping

Revision ID: c1ffd39f8771
Revises: 6dfba72a1cb7
Create Date: 2026-09-07 11:44:30.317491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1ffd39f8771'
down_revision = '6dfba72a1cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_ports', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_mapping', schema=None) as batch_op:
        batch_op.drop_column('total_ports')

    # ### end Alembic commands ###
